### PR TITLE
Change webpage projects structure + redesign projects page

### PR DESCRIPTION
**Pull request by mourabitiziyad**
image

### CODE REVIEW

**Comment by NingyueZhou** [comment]
I noticed a problem: Cannot open the project page by clicking on top bar
image

**Review by NingyueZhou — COMMENTED** [review]
Seeing this warning if run "npm run dev", not sure if relevant
image

**Comment by NingyueZhou** [comment]
Can we display text on this card? Would be more clear what is does at first glance
image

**Comment by mourabitiziyad** [comment]
> Seeing this warning if run "npm run dev", not sure if relevant image

Couldn't re-produce the error, assuming that later changes could have removed it.

**Comment by mourabitiziyad** [comment]
> Can we display text on this card? Would be more clear what is does at first glance image

Updated to 

image

**Comment by mourabitiziyad** [comment]
> I noticed a problem: Cannot open the project page by clicking on top bar image

Solved

**Pull request merged**
