### PR TITLE
Implementing Assessment

### PR DESCRIPTION
**Pull request by mourabitiziyad**
Please test out the functionality. 

I have some bugs lined up / inconsistencies that I will look into:
- ~~Comment disappears after changing the slider.~~
- ~~Comments may not re-appear on reload or do not get stored.~~

Please let me know if you can recreate these issues above and if there are other issues you notice during testing.

Try the following:
- Assessing multiple projects on multiple stages. 
- Do not necessarily fill all the fields and checkmarks, write some random comments.
- After a successful submission, you should be able to see and modify what you submitted, test that it works by navigating to other stages an refreshing the page.

displaying the scores on the charts will follow

### CODE REVIEW

**Comment by NingyueZhou** [comment]
Just some minor comments on UI details, could be last minute fixes or just be ignored (low prio). 

1. Add button to expand/collapse all questions

2. Would be more intuitive to have a searchable drop-down here
image

3. If I don't have the right to create a new project as an assessee, hide the add new project card from assessees (it shows that a new project is successfully created, but I don't have the right to access it...)
image

4. Add crawl, walk, ... (answer levels) below the slider
5. If hover over the area name, it shows a line under the name, gives me the impression that it is clickable, but nothing happens after clicking on it
image

6. Do we really need the gray description text under the checkbox?
image

7. Maybe add `Qustion 1: `, `Question 2: `, ... before every question
image

**Review by NingyueZhou — APPROVED** [review]
Tested the flow described in the PR description, everything works! Really nice job!
But only tested with 1 project that is assigned to me, not sure if everything works with multiple projects at the same time

**Comment by mourabitiziyad** [comment]
> Just some minor comments on UI details, could be last minute fixes or just be ignored (low prio).
> 
> 1. Add button to expand/collapse all questions
> 2. Would be more intuitive to have a searchable drop-down here
>    image
> 3. If I don't have the right to create a new project as an assessee, hide the add new project card from assessees (it shows that a new project is successfully created, but I don't have the right to access it...)
>    image
> 4. Add crawl, walk, ... (answer levels) below the slider
> 5. If hover over the area name, it shows a line under the name, gives me the impression that it is clickable, but nothing happens after clicking on it
>    image
> 6. Do we really need the gray description text under the checkbox?
>    image
> 7. Maybe add `Qustion 1: `, `Question 2: `, ... before every question
>    image

1. All questions will remain open now. No more collapsibility. Got some issues with components unmounting while working on that. Plus the feedback of not wanting to see everything in a collapsed manner, might as well just get rid of it.

2. Not sure what you mean by this. My assumption is that the current version of this consists of a searchable dropdown.

3. You will not have access to a project you created because you didn't assign yourself to it. self-assignment is not something that I think is crucial for the demo.

4. Done.

5. Can remove it, I don't think it bothers much

6. I think it helps to provide a little more context to the checkbox.

7. I think that could be redundant since those questions are already questions. Plus some questions are pretty long so I wouldn't want to add a repetitive prefix to them.

Thanks for reviewing!

**Comment by mourabitiziyad** [comment]
> Just some minor comments on UI details, could be last minute fixes or just be ignored (low prio).
> 
> 1. Add button to expand/collapse all questions
> 2. Would be more intuitive to have a searchable drop-down here
>    image
> 3. If I don't have the right to create a new project as an assessee, hide the add new project card from assessees (it shows that a new project is successfully created, but I don't have the right to access it...)
>    image
> 4. Add crawl, walk, ... (answer levels) below the slider
> 5. If hover over the area name, it shows a line under the name, gives me the impression that it is clickable, but nothing happens after clicking on it
>    image
> 6. Do we really need the gray description text under the checkbox?
>    image
> 7. Maybe add `Qustion 1: `, `Question 2: `, ... before every question
>    image

That page is not hiding the add project button because you are NOT in the projects page to be seeing that. That page is the projects details page refusing to show you the content of THAT project because you're not allowed to see it.

I think it would be an expected behavior from the user to just navigate to a different button or press the browser back button to see the projects.

**Pull request merged**
